import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import clientsRouter from "./clients";
import exercisesRouter from "./exercises";
import programsRouter from "./programs";
import workoutLogsRouter from "./workout_logs";
import measurementsRouter from "./measurements";
import sleepLogsRouter from "./sleep_logs";
import nutritionLogsRouter from "./nutrition_logs";
import progressPhotosRouter from "./progress_photos";
import assignmentsRouter from "./assignments";
import messagesRouter from "./messages";
import dashboardRouter from "./dashboard";
import uploadRouter from "./upload";
import storageRouter from "./storage";
import nutritionExtractRouter from "./nutrition_extract";
import coachNotesRouter from "./coach_notes";
import callLogsRouter from "./call_logs";
import videoCallRouter from "./video_call";
import feedbackRouter from "./feedback";
import surveyRouter from "./survey";
import inviteRouter from "./invite";
import nutritionGoalsRouter from "./nutrition_goals";
import coachSettingsRouter from "./coach_settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(clientsRouter);
router.use(exercisesRouter);
router.use(programsRouter);
router.use(workoutLogsRouter);
router.use(measurementsRouter);
router.use(sleepLogsRouter);
router.use(nutritionLogsRouter);
router.use(progressPhotosRouter);
router.use(assignmentsRouter);
router.use(messagesRouter);
router.use(dashboardRouter);
router.use(uploadRouter);
router.use(storageRouter);
router.use(nutritionExtractRouter);
router.use(coachNotesRouter);
router.use(callLogsRouter);
router.use(videoCallRouter);
router.use(feedbackRouter);
router.use(surveyRouter);
router.use(inviteRouter);
router.use(nutritionGoalsRouter);
router.use(coachSettingsRouter);

export default router;
