// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ToneTester.tsx": () => import("../components/mockups/ToneTester.tsx"),
  "./components/mockups/traklogo/Badge.tsx": () => import("../components/mockups/traklogo/Badge.tsx"),
  "./components/mockups/traklogo/IconText.tsx": () => import("../components/mockups/traklogo/IconText.tsx"),
  "./components/mockups/traklogo/Monogram.tsx": () => import("../components/mockups/traklogo/Monogram.tsx"),
  "./components/mockups/traklogo/Wordmark.tsx": () => import("../components/mockups/traklogo/Wordmark.tsx")
};
